### User 로그인
POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email": "user02@example.com",
  "password": "12345678"
}

### 상품 등록
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ZDI0MDY2MS1lNDhhLTRjODgtYmNhYi1iMWQ3MzNmOWUzNTgiLCJpYXQiOjE3MzQ1NzI1MDcsImV4cCI6MTczNDU3NjEwN30.pVxM9ZBkis6liBNsKT_lb2hJZ2-cFZiBDU2uLyzUmhI

{
  "name": "Stylish Watch9",
  "description": "A trendy and elegant watch.9",
  "price": 100000,
  "images": [],
  "tags": ["fashion", "accessory"]
}

### 상품 목록 조회
GET http://localhost:3000/products

###
GET http://localhost:3000/products?page=1&pageSize=5

###
GET http://localhost:3000/products?page=1&pageSize=3&orderBy=favorite&keyword=watch

### 상품 상세 조회
GET http://localhost:3000/products/b4223803-6d62-4e2c-b7e4-0fc48e6ddd35